Bugfix: inv/attachment
RuntimeException: Route inv/attachment expects at least argument values for [_language,id], but received [_language]

Solution: Update the session variable inv_id in the invController's function url_key